package com.craftworld.game.ui;
import android.content.*; import android.graphics.*; import android.view.*; import com.craftworld.game.engine.GameState; import com.craftworld.game.player.Inventory;
/** Resolution-independent touch HUD: joystick, look pad, actions, survival bars and hotbar. */
public final class HudView extends View {
 private final GameState g; private final Paint p=new Paint(3); private int moveId=-1,lookId=-1; private float mx,my,lx,ly;
 public HudView(Context c,GameState game){super(c);g=game;p.setTypeface(Typeface.DEFAULT_BOLD);setKeepScreenOn(true);}
 protected void onDraw(Canvas c){float w=getWidth(),h=getHeight(),u=Math.min(w,h)/10f;p.setColor(0x77202020);c.drawCircle(u*1.5f,h-u*1.5f,u,p);c.drawCircle(w-u*1.25f,h-u*1.35f,u*.52f,p);c.drawCircle(w-u*2.4f,h-u*.75f,u*.42f,p);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(u*.34f);p.setColor(Color.WHITE);c.drawText("MOVE",u*1.5f,h-u*1.45f,p);c.drawText("JUMP",w-u*1.25f,h-u*1.3f,p);c.drawText("BUILD",w-u*2.4f,h-u*.7f,p);p.setTextAlign(Paint.Align.LEFT);p.setTextSize(u*.34f);c.drawText("♥ "+g.player.health+"   🍗 "+g.player.hunger,20,u*.48f,p);p.setColor(0xAA111111);c.drawRect(w/2-u*2.7f,h-u*.58f,w/2+u*2.7f,h,p);for(int i=0;i<9;i++){float x=w/2-u*2.55f+i*u*.57f;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(i==g.player.inventory.selected?5:2);p.setColor(i==g.player.inventory.selected?Color.WHITE:0x99999999);c.drawRect(x,h-u*.54f,x+u*.5f,h-u*.04f,p);p.setStyle(Paint.Style.FILL);Inventory.Stack s=g.player.inventory.get(i);if(s!=null){p.setColor(0xff000000|s.block.rgb);c.drawRect(x+6,h-u*.54f+6,x+u*.5f-6,h-u*.04f-6,p);}}p.setColor(Color.WHITE);p.setStrokeWidth(3);c.drawLine(w/2-12,h/2,w/2+12,h/2,p);c.drawLine(w/2,h/2-12,w/2,h/2+12,p);invalidate();}
 public boolean onTouchEvent(android.view.MotionEvent e){float w=getWidth(),h=getHeight(),u=Math.min(w,h)/10f;int action=e.getActionMasked(),idx=e.getActionIndex(),id=e.getPointerId(idx);if(action==MotionEvent.ACTION_DOWN||action==MotionEvent.ACTION_POINTER_DOWN){float x=e.getX(idx),y=e.getY(idx);if(y>h-u*.65f&&x>w/2-u*3&&x<w/2+u*3){g.player.inventory.selected=Math.max(0,Math.min(8,(int)((x-(w/2-u*2.55f))/(u*.57f))));return true;}if(dist(x,y,w-u*1.25f,h-u*1.35f)<u*.75f){g.jump=true;return true;}if(dist(x,y,w-u*2.4f,h-u*.75f)<u*.62f){g.interact(true);return true;}if(x<w*.38f){moveId=id;mx=x;my=y;}else{lookId=id;lx=x;ly=y;}}else if(action==MotionEvent.ACTION_MOVE){for(int i=0;i<e.getPointerCount();i++){int q=e.getPointerId(i);float x=e.getX(i),y=e.getY(i);if(q==moveId){g.moveX=clamp((x-mx)/u);g.moveZ=clamp((my-y)/u);}if(q==lookId){g.lookDX+=x-lx;g.lookDY+=y-ly;lx=x;ly=y;}}}else if(action==MotionEvent.ACTION_UP||action==MotionEvent.ACTION_POINTER_UP||action==MotionEvent.ACTION_CANCEL){if(id==moveId){moveId=-1;g.moveX=g.moveZ=0;}if(id==lookId)lookId=-1;}return true;}
 private float clamp(float v){return Math.max(-1,Math.min(1,v));}private float dist(float a,float b,float c,float d){return (float)Math.hypot(a-c,b-d);}
}
