package com.craftworld3d.render;
import android.opengl.*;import com.craftworld3d.world.*;import com.craftworld3d.player.Player;import java.nio.*;import java.util.*;
/** Minimal GLES 3 renderer. Faces are emitted only when their neighbor is transparent. */
public final class VoxelRenderer implements GLSurfaceView.Renderer {
 private final World world; private final Player player; private int program; private FloatBuffer mesh; private int count; private final float[] proj=new float[16],view=new float[16],vp=new float[16];
 private static final String VS="#version 300 es\nin vec3 p;in vec3 c;uniform mat4 vp;out vec3 col;void main(){gl_Position=vp*vec4(p,1.0);col=c;}";
 private static final String FS="#version 300 es\nprecision mediump float;in vec3 col;out vec4 outColor;uniform float light;void main(){outColor=vec4(col*light,1.0);}";
 public VoxelRenderer(World w,Player p){world=w;player=p;}
 public void onSurfaceCreated(javax.microedition.khronos.egl.EGLConfig c){program=Shader.make(VS,FS);GLES30.glEnable(GLES30.GL_DEPTH_TEST);GLES30.glClearColor(.45f,.7f,.95f,1);}
 public void onSurfaceChanged(javax.microedition.khronos.opengles.GL10 g,int w,int h){GLES30.glViewport(0,0,w,h);Matrix.perspectiveM(proj,0,70,(float)w/h,.1f,300);}
 public void onDrawFrame(javax.microedition.khronos.opengles.GL10 g){GLES30.glClear(GLES30.GL_COLOR_BUFFER_BIT|GLES30.GL_DEPTH_BUFFER_BIT);Matrix.setLookAtM(view,0,player.x,player.y+1.6f,player.z,player.x+(float)Math.sin(player.yaw),player.y+1.6f+(float)Math.sin(player.pitch),player.z-(float)Math.cos(player.yaw),0,1,0);Matrix.multiplyMM(vp,0,proj,0,view,0);build(); if(count==0)return; GLES30.glUseProgram(program);GLES30.glUniformMatrix4fv(GLES30.glGetUniformLocation(program,"vp"),1,false,vp,0);float day=(float)(.35+.65*Math.max(0,Math.sin(world.time*Math.PI*2/24000)));GLES30.glUniform1f(GLES30.glGetUniformLocation(program,"light"),day);int p=GLES30.glGetAttribLocation(program,"p"),c=GLES30.glGetAttribLocation(program,"c");mesh.position(0);GLES30.glVertexAttribPointer(p,3,GLES30.GL_FLOAT,false,24,mesh);GLES30.glEnableVertexAttribArray(p);mesh.position(3);GLES30.glVertexAttribPointer(c,3,GLES30.GL_FLOAT,false,24,mesh);GLES30.glEnableVertexAttribArray(c);GLES30.glDrawArrays(GLES30.GL_TRIANGLES,0,count);}
 private void build(){ArrayList<Float> a=new ArrayList<>();int px=(int)Math.floor(player.x),pz=(int)Math.floor(player.z);for(Chunk ch:world.loaded()){if(Math.abs(ch.cx*16-px)>48||Math.abs(ch.cz*16-pz)>48)continue;for(int x=0;x<16;x++)for(int z=0;z<16;z++)for(int y=0;y<45;y++){BlockType b=BlockType.fromId(ch.get(x,y,z));if(b==BlockType.AIR)continue;int wx=ch.cx*16+x,wz=ch.cz*16+z;face(a,wx,y,wz,b,0,world.getBlock(wx+1,y,wz)==BlockType.AIR);face(a,wx,y,wz,b,1,world.getBlock(wx-1,y,wz)==BlockType.AIR);face(a,wx,y,wz,b,2,world.getBlock(wx,y+1,wz)==BlockType.AIR);face(a,wx,y,wz,b,3,world.getBlock(wx,y-1,wz)==BlockType.AIR);face(a,wx,y,wz,b,4,world.getBlock(wx,y,wz+1)==BlockType.AIR);face(a,wx,y,wz,b,5,world.getBlock(wx,y,wz-1)==BlockType.AIR);}}count=a.size()/6;ByteBuffer bb=ByteBuffer.allocateDirect(a.size()*4).order(ByteOrder.nativeOrder());mesh=bb.asFloatBuffer();for(float v:a)mesh.put(v);mesh.flip();}
 private void face(ArrayList<Float>a,int x,int y,int z,BlockType b,int f,boolean on){if(!on)return;float[][] q={{1,0,0},{0,1,0},{0,0,1}};float[][] v;switch(f){case 0:v=new float[][]{{x+1,y,z},{x+1,y+1,z},{x+1,y+1,z+1},{x+1,y,z+1}};break;case 1:v=new float[][]{{x,y,z+1},{x,y+1,z+1},{x,y+1,z},{x,y,z}};break;case 2:v=new float[][]{{x,y+1,z},{x,y+1,z+1},{x+1,y+1,z+1},{x+1,y+1,z}};break;case 3:v=new float[][]{{x,y,z+1},{x,y,z},{x+1,y,z},{x+1,y,z+1}};break;case 4:v=new float[][]{{x+1,y,z+1},{x+1,y+1,z+1},{x,y+1,z+1},{x,y,z+1}};break;default:v=new float[][]{{x,y,z},{x,y+1,z},{x+1,y+1,z},{x+1,y,z}};}int[] ix={0,1,2,0,2,3};for(int i:ix){a.add(v[i][0]);a.add(v[i][1]);a.add(v[i][2]);a.add(b.r);a.add(b.g);a.add(b.b);}}
 static final class Shader{static int make(String v,String f){int vs=GLES30.glCreateShader(GLES30.GL_VERTEX_SHADER);GLES30.glShaderSource(vs,v);GLES30.glCompileShader(vs);int fs=GLES30.glCreateShader(GLES30.GL_FRAGMENT_SHADER);GLES30.glShaderSource(fs,f);GLES30.glCompileShader(fs);int p=GLES30.glCreateProgram();GLES30.glAttachShader(p,vs);GLES30.glAttachShader(p,fs);GLES30.glLinkProgram(p);return p;}}
}
