package com.craftworld.game.engine;
import android.content.Context; import android.opengl.*; import com.craftworld.game.world.*; import java.nio.*; import javax.microedition.khronos.egl.EGLConfig; import javax.microedition.khronos.opengles.GL10;
/** GLES 3 renderer. Uses depth testing, fog, directional light and a compact reusable cube VBO. */
public final class GameRenderer implements GLSurfaceView.Renderer {
 private final GameState game=new GameState(); private int program,vbo,uMvp,uModel,uColor,uSun; private final float[] proj=new float[16],view=new float[16],vp=new float[16],model=new float[16],mvp=new float[16]; private long last;
 private static final float[] CUBE={
 0,0,1,0,0,1, 1,0,1,0,0,1, 1,1,1,0,0,1, 0,0,1,0,0,1, 1,1,1,0,0,1, 0,1,1,0,0,1,
 1,0,0,0,0,-1, 0,0,0,0,0,-1, 0,1,0,0,0,-1, 1,0,0,0,0,-1, 0,1,0,0,0,-1, 1,1,0,0,0,-1,
 0,1,1,0,1,0, 1,1,1,0,1,0, 1,1,0,0,1,0, 0,1,1,0,1,0, 1,1,0,0,1,0, 0,1,0,0,1,0,
 0,0,0,0,-1,0, 1,0,0,0,-1,0, 1,0,1,0,-1,0, 0,0,0,0,-1,0, 1,0,1,0,-1,0, 0,0,1,0,-1,0,
 1,0,1,1,0,0, 1,0,0,1,0,0, 1,1,0,1,0,0, 1,0,1,1,0,0, 1,1,0,1,0,0, 1,1,1,1,0,0,
 0,0,0,-1,0,0, 0,0,1,-1,0,0, 0,1,1,-1,0,0, 0,0,0,-1,0,0, 0,1,1,-1,0,0, 0,1,0,-1,0,0};
 public GameRenderer(Context c){} public GameState getGame(){return game;}
 @Override public void onSurfaceCreated(GL10 gl,EGLConfig cfg){GLES30.glEnable(GLES30.GL_DEPTH_TEST);GLES30.glEnable(GLES30.GL_CULL_FACE);program=link(VS,FS);uMvp=GLES30.glGetUniformLocation(program,"uMvp");uModel=GLES30.glGetUniformLocation(program,"uModel");uColor=GLES30.glGetUniformLocation(program,"uColor");uSun=GLES30.glGetUniformLocation(program,"uSun");int[] b=new int[1];GLES30.glGenBuffers(1,b,0);vbo=b[0];FloatBuffer fb=ByteBuffer.allocateDirect(CUBE.length*4).order(ByteOrder.nativeOrder()).asFloatBuffer();fb.put(CUBE).flip();GLES30.glBindBuffer(GLES30.GL_ARRAY_BUFFER,vbo);GLES30.glBufferData(GLES30.GL_ARRAY_BUFFER,CUBE.length*4,fb,GLES30.GL_STATIC_DRAW);last=System.nanoTime();}
 @Override public void onSurfaceChanged(GL10 gl,int w,int h){GLES30.glViewport(0,0,w,h);Matrix.perspectiveM(proj,0,70,(float)w/h,.1f,180);}
 @Override public void onDrawFrame(GL10 gl){long now=System.nanoTime();float dt=Math.min(.05f,(now-last)/1e9f);last=now;game.tick(dt);float daylight=Math.max(.12f,(float)(Math.sin(game.time*Math.PI*2)*.55+.5));GLES30.glClearColor(.2f*daylight,.45f*daylight,.72f*daylight,1);GLES30.glClear(GLES30.GL_COLOR_BUFFER_BIT|GLES30.GL_DEPTH_BUFFER_BIT);float yaw=(float)Math.toRadians(game.player.yaw),pitch=(float)Math.toRadians(game.player.pitch),cx=(float)(Math.sin(yaw)*Math.cos(pitch)),cy=-(float)Math.sin(pitch),cz=-(float)(Math.cos(yaw)*Math.cos(pitch));Matrix.setLookAtM(view,0,game.player.x,game.player.y,game.player.z,game.player.x+cx,game.player.y+cy,game.player.z+cz,0,1,0);Matrix.multiplyMM(vp,0,proj,0,view,0);GLES30.glUseProgram(program);GLES30.glUniform1f(uSun,daylight);GLES30.glBindBuffer(GLES30.GL_ARRAY_BUFFER,vbo);GLES30.glEnableVertexAttribArray(0);GLES30.glVertexAttribPointer(0,3,GLES30.GL_FLOAT,false,24,0);GLES30.glEnableVertexAttribArray(1);GLES30.glVertexAttribPointer(1,3,GLES30.GL_FLOAT,false,24,12);drawTerrain();}
 private void drawTerrain(){int px=(int)game.player.x,pz=(int)game.player.z;for(int x=px-18;x<=px+18;x++)for(int z=pz-18;z<=pz+18;z++){int top=0;Block b=Block.AIR;for(int y=110;y>0;y--){b=game.world.get(x,y,z);if(b!=Block.AIR&&b!=Block.WATER){top=y;break;}}drawCube(x,top,z,b);if(top<62)drawCube(x,62,z,Block.WATER);}}
 private void drawCube(float x,float y,float z,Block b){Matrix.setIdentityM(model,0);Matrix.translateM(model,0,x,y,z);Matrix.multiplyMM(mvp,0,vp,0,model,0);GLES30.glUniformMatrix4fv(uMvp,1,false,mvp,0);GLES30.glUniformMatrix4fv(uModel,1,false,model,0);GLES30.glUniform3f(uColor,((b.rgb>>16)&255)/255f,((b.rgb>>8)&255)/255f,(b.rgb&255)/255f);GLES30.glDrawArrays(GLES30.GL_TRIANGLES,0,36);}
 private int link(String vs,String fs){int v=shader(GLES30.GL_VERTEX_SHADER,vs),f=shader(GLES30.GL_FRAGMENT_SHADER,fs),p=GLES30.glCreateProgram();GLES30.glAttachShader(p,v);GLES30.glAttachShader(p,f);GLES30.glLinkProgram(p);return p;}private int shader(int type,String src){int s=GLES30.glCreateShader(type);GLES30.glShaderSource(s,src);GLES30.glCompileShader(s);return s;}
 private static final String VS="#version 300 es\nlayout(location=0)in vec3 p;layout(location=1)in vec3 n;uniform mat4 uMvp,uModel;out vec3 N;out float d;void main(){gl_Position=uMvp*vec4(p,1);N=mat3(uModel)*n;d=gl_Position.z;}";
 private static final String FS="#version 300 es\nprecision mediump float;in vec3 N;in float d;uniform vec3 uColor;uniform float uSun;out vec4 o;void main(){float l=max(.28,dot(normalize(N),normalize(vec3(.4,1,.2))))*uSun;float fog=clamp((d-45.)/100.,0.,.72);o=vec4(mix(uColor*l,vec3(.35,.55,.75)*uSun,fog),1);}";
}
